# Run unit tests using CTest
name: Tests
on: [ push ]
jobs:
  run-unit-tests:
    runs-on: cmake
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        uses: HorstBaerbel/action-ctest@1.1
        with:
          cmakeoptions: '-D TESTING=1'
