# Run unit tests using CTest
name: Tests
on: pull_request
jobs:
  unit-tests:
    runs-on: cmake
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        uses: KyryloKupin/action-ctest@master
        with:
          cmakeoptions: '-D TESTING=1'
